# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testwebapps

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://test.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_4601534d033241a5b79feb4187eace05 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c502a45cea3e4e7fa034e8c3cabd2038 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: test.com/${{ secrets.AzureAppService_ContainerUsername_4601534d033241a5b79feb4187eace05 }}/nginx:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testwebapps'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4ed64c429a494456983152992239bcfd }}
        images: 'test.com/${{ secrets.AzureAppService_ContainerUsername_4601534d033241a5b79feb4187eace05 }}/nginx:${{ github.sha }}'